name: "EMHASS Enhanced"
description: "Energy Management for Home Assistant - Enhanced Version"
url: https://github.com/tomvanacker85/emhass-add-on
version: v0.13.5-enhanced #using original base with enhancements
slug: emhass-enhanced
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
image: "ghcr.io/davidusb-geek/emhass" #use working original image base
ports:
  5001/tcp: 5001
ports_description:
  5001/tcp: Web interface and API (Enhanced)
webui: http://[HOST]:[PORT:5001]
map:
  - share:rw
init: false
hassio_role: default
schema:
  hass_url: "str?" #optional
  long_lived_token: "password?" #optional
  data_path: "list(default|/data/|/share)?" #optional
  time_zone: "match((\\w+)?(\\/)(\\w+))?" #optional
  Latitude: "float?" #optional
  Longitude: "float?" #optional
  Altitude: "float?" #optional
  solcast_api_key: "password?" #optional
  solcast_rooftop_id: "str?" #optional
  solar_forecast_kwp: "float?" #optional
  server_ip: "list(0.0.0.0|127.0.0.1)?" #optional
  number_of_ev_loads: "int?" #optional
  ev_battery_capacity: "str?" #optional - JSON array of EV battery capacities in Wh
  ev_charging_efficiency: "str?" #optional - JSON array of EV charging efficiencies (0-1)
  ev_nominal_charging_power: "str?" #optional - JSON array of max EV charging power in W
  ev_minimum_charging_power: "str?" #optional - JSON array of min EV charging power in W
